### ISSUE TITLE
ox_target

### ISSUE THREAD

**Issue by ErinDeveloping** [obi23lipnik/bobi-selldrugs#1]
When I try to sell using ox targte
![image](https://user-images.githubusercontent.com/103432656/236524610-a19a4f18-b3e0-41f4-9767-5e6692041b37.png)

**Comment by obi23lipnik** [comment]
@ErinDeveloping  Issue was just addressed with the latest release: https://github.com/obi23lipnik/bobi-selldrugs/releases/tag/v0.6 

Please give it a try and let me know if you still have the problem
